# Generated by Django 5.2.12 on 2026-03-07 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aichatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPredictedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('time_to_event', models.CharField(max_length=50)),
                ('confidence_score', models.IntegerField()),
                ('recommendation', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_events', to='api.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='AIAnalysis',
        ),
    ]
