# Generated by Django 5.2.12 on 2026-03-07 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aipredictedevent_delete_aianalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField()),
                ('risk_factors', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='api.patient')),
            ],
        ),
    ]
