# Generated by Django 5.2.12 on 2026-03-07 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alert_ai_confidence_alert_current_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_notifications', models.BooleanField(default=True)),
                ('sound', models.BooleanField(default=True)),
                ('vibration', models.BooleanField(default=True)),
                ('spo2_low_limit', models.IntegerField(default=90)),
                ('rr_high_limit', models.IntegerField(default=30)),
                ('pressure_high_limit', models.IntegerField(default=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
