# Generated by Django 5.2.12 on 2026-03-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_faq_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsign',
            name='fio2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='ie_ratio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='peep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='ppeak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='vte',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
