# Generated by Django 5.2.12 on 2026-03-07 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='notes',
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='event_title',
            field=models.CharField(default='Event', max_length=255),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='event_type',
            field=models.CharField(default='info', max_length=50),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
