# Generated by Django 5.2.12 on 2026-03-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_patienthistory_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
