# Generated by Django 5.2.12 on 2026-03-07 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_employee_id_profile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file_size_bytes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='Report', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
