# Generated by Django 5.2.12 on 2026-03-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_profile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
